Update for eww before September
Final commit for eww and project

diff --git a/.config/eww/scripts/net b/.config/eww/scripts/net
--- a/.config/eww/scripts/net
+++ b/.config/eww/scripts/net
@@ -1,3 +1,44 @@
+# #!/usr/bin/env bash
+
+# toggle() {
+#   status=$(rfkill -J | gojq -r '.rfkilldevices[] | select(.type == "wlan") | .soft' | head -1)
+
+#   if [ "$status" = "unblocked" ]; then
+#     rfkill block wlan
+#   else
+#     rfkill unblock wlan
+#   fi
+# }
+
+# if [ "$1" = "toggle" ]; then
+#   toggle
+# else
+#   while true; do
+#     status=$(nmcli g | tail -n 1 | awk '{print $1}')
+#     signal=$(nmcli -f in-use,signal dev wifi | rg "\*" | awk '{ print $2 }')
+#     essid=$(nmcli -t -f NAME connection show --active | head -n1 | sed 's/\"/\\"/g')
+
+#     icons=("" "" "" "" "")
+
+#     if [ "$status" = "disconnected" ] ; then
+#       icon=""
+#       color="#988ba2"
+#     else
+#       level=$(awk -v n="$signal" 'BEGIN{print int((n-1)/20)}')
+#       if [ "$level" -gt 4 ]; then
+#         level=4
+#       fi
+
+#       icon=${icons[$level]}
+#       color="#cba6f7"
+#     fi
+
+#     echo '{ "essid": "'"$essid"'", "icon": "'"$icon"'", "color": "'"$color"'", "level": "'"$level"'" }'
+
+#     sleep 4
+#   done
+# fi
+
 #!/usr/bin/env bash
 
 toggle() {
@@ -21,6 +62,7 @@ else
     icons=("" "" "" "" "")
 
     if [ "$status" = "disconnected" ] ; then
+      level=0
       icon=""
       color="#988ba2"
     else
@@ -40,12 +82,9 @@ else
 fi
 
 # #!/usr/bin/env bash
-
-# LOGFILE="${HOME}/.config/eww/net.log"
-
 # nm_is_running() {
-#   if ! timeout 2 nmcli -t -f RUNNING general status >/dev/null 2>>"$LOGFILE"; then
-#     echo "Error: NetworkManager is not running" >> "$LOGFILE"
+#   if ! timeout 2 nmcli -t -f RUNNING general status >/dev/null; then
+#     echo "Error: NetworkManager is not running"
 #     exit 1
 #   fi
 # }
@@ -54,10 +93,10 @@ fi
 #   wifi_status=$(timeout 2 nmcli radio wifi)
 #   if [ "$wifi_status" = "enabled" ]; then
 #     timeout 2 nmcli radio wifi off
-#     echo "Wi-Fi turned OFF" >> "$LOGFILE"
+#     echo "Wi-Fi turned OFF"
 #   else
 #     timeout 2 nmcli radio wifi on
-#     echo "Wi-Fi turned ON" >> "$LOGFILE"
+#     echo "Wi-Fi turned ON"
 #   fi
 # }
 
@@ -66,10 +105,10 @@ fi
 #   state=$(timeout 2 nmcli device status | awk -v dev="$device" '$1 == dev {print $3}')
 #   if [ "$state" = "connected" ]; then
 #     timeout 2 nmcli device disconnect "$device"
-#     echo "Ethernet $device disconnected" >> "$LOGFILE"
+#     echo "Ethernet $device disconnected"
 #   elif [ "$state" = "disconnected" ]; then
 #     timeout 2 nmcli device connect "$device"
-#     echo "Ethernet $device connected" >> "$LOGFILE"
+#     echo "Ethernet $device connected"
 #   fi
 # }
 
@@ -88,7 +127,7 @@ fi
 #     toggle_eth "$active_eth"
 #   else
 #     timeout 2 nmcli radio wifi on
-#     echo "No connection, Wi-Fi turned ON" >> "$LOGFILE"
+#     echo "No connection, Wi-Fi turned ON"
 #   fi
 # }
 
